# Generated by Django 4.0.3 on 2022-04-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_note_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
